# vPostgres
# /storage/db/vpostgres/postgresql.conf
var_postgres_conf_log_line_prefix: "'%m %c %x %d %u %r %p %l '"
var_postgres_conf_log_truncate_on_rotation: "on"
var_postgres_conf_port: 5432
var_postgres_conf_ssl: "on"
var_postgres_conf_ssl_ciphers: "'!aNULL:kECDH+AES:ECDH+AES:RSA+AES:@STRENGTH'"
var_postgres_conf_fsync: "on"
var_postgres_conf_full_page_writes: "on"
var_postgres_conf_synchronous_commit: "on"
var_postgres_conf_client_min_messages: "notice"
var_postgres_conf_logging_collector: "on"
var_postgres_conf_log_destination: "'stderr'"
var_postgres_conf_log_timezone: "'UTC'"
var_postgres_conf_client_encoding: "UTF8"
var_postgres_conf_log_connections: "on"
var_postgres_conf_log_disconnections: "on"
