# VMware vSphere 6.7 vCenter Server Appliance vSphere UI Ansible Playbook

---

 # ---------- Ansible version 2.12 -------- #


############################################

# Title: vSphere UI must limit the amount of time that each TCP connection is kept alive

- name: VCUI-67-000001 - vSphere UI must limit the amount of time that each TCP connection is kept alive
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector'
    attribute: 'connectionTimeout'
    value: '{{ var_server_xml_connectiontimeout }}'
  tags:
    - VCUI-67-000001
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_connection_timeout | bool

############################################

# Title: vSphere UI must limit the number of concurrent connections permitted

- name: VCUI-67-000002 - vSphere UI must limit the number of concurrent connections permitted
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Executor'
    attribute: 'maxThreads'
    value: '{{ var_server_xml_maxthreads }}'
  tags:
    - VCUI-67-000002
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_max_threads | bool

############################################

# Title: vSphere UI must limit the maximum size of a POST request

- name: VCUI-67-000003 - vSphere UI must limit the maximum size of a POST request
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector/@maxPostSize'
    state: absent
  tags:
    - VCUI-67-000003
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_max_post_size | bool

############################################

# Title: vSphere UI must protect cookies from XSS

- name: VCUI-67-000004 - vSphere UI must protect cookies from XSS
  community.general.xml:
    path: '{{ var_context_xml_path }}'
    xpath: '/Context'
    attribute: 'useHttpOnly'
    value: '{{ var_context_xml_http_only }}'
  tags:
    - VCUI-67-000004
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_http_only | bool

############################################

# Title: vSphere UI must record user access in a format that enables monitoring of remote access

- name: VCUI-67-000005 - vSphere UI must record user access in a format that enables monitoring of remote access
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.AccessLogValve"]'
    attribute: 'pattern'
    value: '{{ var_server_xml_access_log_valve_pattern }}'
  tags:
    - VCUI-67-000005
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_access_valve_pattern | bool

############################################

# Title: vSphere UI must generate log records for system startup and shutdown

- name: VCUI-67-000006 - vSphere UI must generate log records for system startup and shutdown
  ansible.builtin.lineinfile:
    path: '{{ var_json_path }}'
    state: present
    regexp: '^.*"StreamRedirectFile".*$'
    line: '    "StreamRedirectFile" : "{{ var_json_stream_redirect_file }}",'
    insertbefore: ^.*WorkingDir.*$
    firstmatch: true
  tags:
    - VCUI-67-000006
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_json_stream_redirect_file | bool

############################################

# Title: vSphere UI log files must only be modifiable by privileged users

- name: VCUI-67-000007 - Find vSphere UI log files
  ansible.builtin.find:
    paths: '{{ var_logs_path }}'
    file_type: file
  register: vspherelogs
  tags:
    - VCUI-67-000007
    - vsphere-ui
  when:
    - run_logs_permissions | bool

- name: VCUI-67-000007 - Set vSphere UI log permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    mode: "0600"
    owner: "vsphere-ui"
    group: "users"
  with_items: "{{ vspherelogs.files }}"
  tags:
    - VCUI-67-000007
    - vsphere-ui
  when:
    - run_logs_permissions | bool

############################################

# Title: vSphere UI application files must be verified for their integrity
# VCUI-67-000008 requires manual remediation

############################################

# Title: vSphere UI plugins must be authorized before use.
# VCUI-67-000009 requires manual remediation

############################################

# Title: vSphere UI must be configured to limit access to internal packages.

- name: VCUI-67-000010 - vSphere UI must be configured to limit access to internal packages.
  community.general.ini_file:
    path: '{{ var_catalina_props_path }}'
    section: null
    state: present
    no_extra_spaces: true
    option: 'package.access'
    value: '{{ var_catalina_props_package_access }}'
  tags:
    - VCUI-67-000010
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_catalina_props_package_access | bool


############################################

# Title: vSphere UI must have Multipurpose Internet Mail Extensions (MIME) that invoke OS shell programs disabled

- name: VCUI-67-000011 - vSphere UI must have Multipurpose Internet Mail Extensions (MIME) that invoke OS shell programs disabled CSH
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:mime-mapping/x:extension[text()="csh"]/..'
    state: absent
    namespaces:
      x: http://java.sun.com/xml/ns/javaee
  tags:
    - VCUI-67-000011
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_removed_mime_mappings | bool

- name: VCUI-67-000011 - vSphere UI must have Multipurpose Internet Mail Extensions (MIME) that invoke OS shell programs disabled SH
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:mime-mapping/x:extension[text()="sh"]/..'
    state: absent
    namespaces:
      x: http://java.sun.com/xml/ns/javaee
  tags:
    - VCUI-67-000011
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_removed_mime_mappings | bool

- name: VCUI-67-000011 - vSphere UI must have Multipurpose Internet Mail Extensions (MIME) that invoke OS shell programs disabled SHAR
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:mime-mapping/x:extension[text()="shar"]/..'
    state: absent
    namespaces:
      x: http://java.sun.com/xml/ns/javaee
  tags:
    - VCUI-67-000011
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_removed_mime_mappings | bool

- name: VCUI-67-000011 - vSphere UI must have Multipurpose Internet Mail Extensions (MIME) that invoke OS shell programs disabled KSH
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:mime-mapping/x:extension[text()="ksh"]/..'
    state: absent
    namespaces:
      x: http://java.sun.com/xml/ns/javaee
  tags:
    - VCUI-67-000011
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_removed_mime_mappings | bool

############################################

# Title: vSphere UI must have mappings set for Java servlet pages.

- name: VCUI-67-000012 - vSphere UI must have mappings set for Java servlet pages. jsp
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:servlet-mapping[x:servlet-name="jsp"]/x:url-pattern[1]'
    value: '{{ var_web_xml_servlet_jsp_url_pattern1 }}'
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000012
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_java_servlet | bool

- name: VCUI-67-000012 - vSphere UI must have mappings set for Java servlet pages. jspx
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:servlet-mapping[x:servlet-name="jsp"]/x:url-pattern[2]'
    value: '{{ var_web_xml_servlet_jsp_url_pattern2 }}'
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000012
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_java_servlet | bool

############################################

# Title: vSphere UI must not have the Web Distributed Authoring (WebDAV) servlet installed.

- name: VCUI-67-000013 - vSphere UI must not have the Web Distributed Authoring (WebDAV) servlet installed.
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:servlet-mapping[x:servlet-name="webdav"]/..'
    state: absent
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000013
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_remove_webdav | bool

############################################

# Title: vSphere UI must be configured with memory leak protection.

- name: VCUI-67-000014 - vSphere UI must be configured with memory leak protection.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Listener[@className="org.apache.catalina.core.JreMemoryLeakPreventionListener"]'
    state: present
  tags:
    - VCUI-67-000014
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_mem_leak_prevention | bool

############################################

# Title: vSphere UI must not have any symbolic links in the web content directory tree.
# VCUI-67-000015 requires manual remediation

############################################

# Title: vSphere UI directory tree must have permissions in an "out of the box" state.

- name: VCUI-67-000016 - Find vSphere UI web files
  ansible.builtin.shell: find {{ var_files_web_path }} -xdev -type f -a '(' -perm -o+w -o -not -user vsphere-ui -o -not -group root ')';
  register: files
  tags:
    - VCUI-67-000016
    - vsphere-ui
  changed_when: files.stdout!=""
  when:
    - run_web_files_permissions | bool

- name: VCUI-67-000016 - Set vSphere UI web files owner and group
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
    mode: o-w
    owner: "vsphere-ui"
    group: "root"
  with_items: "{{ files.stdout_lines }}"
  tags:
    - VCUI-67-000016
    - vsphere-ui
  when:
    - run_web_files_permissions | bool
    - files.stdout != ""

############################################

# Title: vSphere UI must fail to a known safe state if system initialization fails, shutdown fails, or aborts fail.

- name: VCUI-67-000017 - vSphere UI must fail to a known safe state if system initialization fails, shutdown fails, or aborts fail.
  community.general.ini_file:
    path: '{{ var_catalina_props_path }}'
    section: null
    state: present
    no_extra_spaces: true
    option: 'org.apache.catalina.startup.EXIT_ON_INIT_FAILURE'
    value: '{{ var_catalina_props_init_failure }}'
  tags:
    - VCUI-67-000017
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_catalina_props_init_failure | bool

############################################

# Title: vSphere UI must limit the number of allowed connections.

- name: VCUI-67-000018 - vSphere UI must limit the number of allowed connections.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector'
    attribute: 'acceptCount'
    value: '{{ var_server_xml_acceptcount }}'
  tags:
    - VCUI-67-000018
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_accept_count | bool

############################################

# Title: vSphere UI must set URIEncoding to UTF-8.

- name: VCUI-67-000019 - vSphere UI must set URIEncoding to UTF-8.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector'
    attribute: 'URIEncoding'
    value: '{{ var_server_xml_uriencoding }}'
  tags:
    - VCUI-67-000019
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_uri_encoding | bool

############################################

# Title: vSphere UI must set the welcome-file node to a default web page.

- name: VCUI-67-000020 - vSphere UI must set the welcome-file node to a default web page. html
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:welcome-file-list/x:welcome-file[1]'
    value: '{{ var_web_xml_welcome_file_list1 }}'
    state: present
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000020
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_welcome_file | bool

- name: VCUI-67-000020 - vSphere UI must set the welcome-file node to a default web page. htm
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:welcome-file-list/x:welcome-file[2]'
    value: '{{ var_web_xml_welcome_file_list2 }}'
    state: present
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000020
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_welcome_file | bool

- name: VCUI-67-000020 - vSphere UI must set the welcome-file node to a default web page. jsp
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:welcome-file-list/x:welcome-file[3]'
    value: '{{ var_web_xml_welcome_file_list3 }}'
    state: present
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000020
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_welcome_file | bool

############################################

# Title: vSphere UI must not show directory listings.

- name: VCUI-67-000021 - vSphere UI must not show directory listings.
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:servlet/x:init-param/x:param-name[text()="listings"]/..'
    state: absent
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000021
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_remove_listings | bool

############################################

# Title: vSphere UI must be configured to hide the server version.

- name: VCUI-67-000022 - vSphere UI must be configured to hide the server version.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector'
    attribute: 'server'
    value: '{{ var_server_xml_server }}'
  tags:
    - VCUI-67-000022
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_min_info | bool

############################################

# Title: vSphere UI must be configured to show error pages with minimal information.

- name: VCUI-67-000023 - vSphere UI must be configured to show error pages with minimal information.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.ErrorReportValve"]'
    attribute: 'showServerInfo'
    value: '{{ var_server_xml_show_server_info }}'
  tags:
    - VCUI-67-000023
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_show_server_info | bool

############################################

# Title: vSphere UI must not enable support for TRACE requests.

- name: VCUI-67-000024 - vSphere UI must not enable support for TRACE requests.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector/@allowTrace'
    state: absent
  tags:
    - VCUI-67-000024
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_allow_trace | bool

############################################

# Title: vSphere UI must have the debug option turned off.

- name: VCUI-67-000025 - vSphere UI must have the debug option turned off.
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:servlet/x:init-param/x:param-name[text()="debug"]/..'
    state: absent
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000025
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_remove_debug | bool

############################################

# Title: vSphere UI must use a logging mechanism that is configured to allocate log record storage capacity large enough to accommodate the logging requirements of the web server.
# VCUI-67-000026 requires manual remediation

############################################

# Title: Rsyslog must be configured to monitor and ship vSphere UI log files.

- name: VCUI-67-000027 - Rsyslog must be configured to monitor and ship vSphere UI log files.
  ansible.builtin.template:
    src: stig-services-vsphere-ui.conf.j2
    dest: /etc/vmware-syslog/stig-services-vsphere-ui.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  tags:
    - VCUI-67-000027
    - vsphere-ui
  notify:
    - restart syslog
  when:
    - run_syslog_config | bool

############################################

# Title: vSphere UI must must be configured with the appropriate ports.

- name: VCUI-67-000028 - vSphere UI must must be configured with the appropriate ports. http
  community.general.ini_file:
    path: '{{ var_catalina_props_path }}'
    section: null
    state: present
    no_extra_spaces: true
    option: 'http.port'
    value: '{{ var_catalina_props_ports_http }}'
  tags:
    - VCUI-67-000028
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_catalina_props_ports | bool

- name: VCUI-67-000028 - vSphere UI must must be configured with the appropriate ports. https
  community.general.ini_file:
    path: '{{ var_catalina_props_path }}'
    section: null
    state: present
    no_extra_spaces: true
    option: 'https.port'
    value: '{{ var_catalina_props_ports_https }}'
  tags:
    - VCUI-67-000028
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_catalina_props_ports | bool

- name: VCUI-67-000028 - vSphere UI must must be configured with the appropriate ports. proxy
  community.general.ini_file:
    path: '{{ var_catalina_props_path }}'
    section: null
    state: present
    no_extra_spaces: true
    option: 'proxy.port'
    value: '{{ var_catalina_props_ports_proxy }}'
  tags:
    - VCUI-67-000028
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_catalina_props_ports | bool

############################################

# Title: vSphere UI must disable the shutdown port.

- name: VCUI-67-000029 - vSphere UI must disable the shutdown port.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server'
    attribute: 'port'
    value: '{{ var_server_xml_shutdown_port }}'
  tags:
    - VCUI-67-000029
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_server_shutdownport | bool

############################################

# Title: vSphere UI must set the secure flag for cookies.

- name: VCUI-67-000030 - vSphere UI must set the secure flag for cookies.
  community.general.xml:
    path: '{{ var_web_xml_path }}'
    xpath: '/x:web-app/x:session-config/x:cookie-config/x:secure'
    value: '{{ var_web_xml_cookie_secure }}'
    namespaces:
      x: http://xmlns.jcp.org/xml/ns/javaee
  tags:
    - VCUI-67-000030
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_web_cookie_secure | bool

############################################

# Title: vSphere UI must not be configured with the UserDatabaseRealm enabled.

- name: VCUI-67-000031 - Remove GlobalNamingResources
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/GlobalNamingResources'
    state: absent
  tags:
    - VCUI-67-000031
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_user_database_realm | bool

- name: VCUI-67-000031 - Remove Realm
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Engine/Realm'
    state: absent
  tags:
    - VCUI-67-000031
    - vsphere-ui
  notify:
    - restart vsphere-ui
  when:
    - run_user_database_realm | bool
