---

# Turn specific controls on/off by setting the value to true or false

# VCRP-67-000001
run_config_idletimesec: true
# VCRP-67-000002
run_config_maxconnections: true
# VCRP-67-000003
run_config_fips: true
# VCRP-67-000004
run_config_remove_protocols: true
# VCRP-67-000005
run_config_log_level: true
# VCRP-67-000006
run_config_log_files: true
# VCRP-67-000007
run_key_permissions: true
# VCRP-67-000008
run_config_ssl: true
# VCRP-67-000009
run_syslog_config: true
