# vsphere-ui variables

# server.xml variables
var_server_xml_path: '/usr/lib/vmware-vsphere-ui/server/conf/server.xml'
var_server_xml_connectiontimeout: '300000'
var_server_xml_maxthreads: '800'
# This may need special escaping if special characters are used like & and {# #}  {% raw %} and {% endraw %} at the beginning and end will get most of it
# Also & needs to just be a " which turns into &quot
var_server_xml_access_log_valve_pattern: '{% raw %}%h %{x-forwarded-for}i %l %u %t "%r" %s %b %{#hashedSessionId#}s %I %D{% endraw %}'
var_server_xml_acceptcount: '300'
var_server_xml_uriencoding: 'UTF-8'
var_server_xml_server: 'Anonymous'
var_server_xml_show_server_info: 'false'
var_server_xml_shutdown_port: '${shutdown.port}'

# context.xml variables
var_context_xml_path: '/usr/lib/vmware-vsphere-ui/server/conf/context.xml'
var_context_xml_http_only: 'true'

# catalina.properties variables
var_catalina_props_path: '/usr/lib/vmware-vsphere-ui/server/conf/catalina.properties'
var_catalina_props_package_access: 'sun.,org.apache.catalina.,org.apache.coyote.,org.apache.jasper.,org.apache.tomcat.'
var_catalina_props_init_failure: 'true'
var_catalina_props_ports_http: '5090'
var_catalina_props_ports_https: '5443'
var_catalina_props_ports_proxy: '443'

# web.xml variables
var_web_xml_path: '/usr/lib/vmware-vsphere-ui/server/conf/web.xml'
var_web_xml_servlet_jsp_url_pattern1: '*.jsp'
var_web_xml_servlet_jsp_url_pattern2: '*.jspx'
var_web_xml_welcome_file_list1: 'index.html'
var_web_xml_welcome_file_list2: 'index.htm'
var_web_xml_welcome_file_list3: 'index.jsp'
var_web_xml_cookie_secure: 'true'

# json variables
var_json_path: '/etc/vmware/vmware-vmon/svcCfgfiles/vsphere-ui.json'
var_json_stream_redirect_file: '%VMWARE_LOG_DIR%/vmware/vsphere-ui/logs/vsphere-ui-runtime.log'

# log variables
var_logs_path: '/storage/log/vmware/vsphere-ui/logs'

# misc variables
var_files_web_path: '/usr/lib/vmware-vsphere-ui/server/lib /usr/lib/vmware-vsphere-ui/server/conf'
